#!/usr/bin/env perl
use Mojolicious::Lite;
use Time::HiRes 'time';

get '/' => 'index';

my %clients;
websocket '/echo' => sub {
    my $self = shift;
    my $log  = $self->app->log;
    my $id   = time;

    $clients{$id} = $self->tx;
    $log->debug('[ws] client connected');
    $self->on(
        message => sub {
            my ( $self, $msg ) = @_;
            $log->debug("[ws] < $msg");
            for my $key ( keys %clients ) {
                $clients{$key}->send($msg);
                $log->debug("[ws] > ($id) $msg");
            }
        }
    );

    $self->on(
        finish => sub {
            $log->debug('[ws] client disconnected');
            delete $clients{$id};
        }
    );
};

app->start;

__DATA__

@@ index.html.ep

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Echo client</title>
    <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
    <script>
      $(function() {
        var sock;
        var port = location.port;
        sock = new WebSocket('ws://localhost:' + port + '/echo');
        sock.onopen = function(e) {
          console.log('Connected');
        }
        sock.onmessage = function(e) {
          $('<p>' + e.data + '</p>').appendTo('#msg');
        };

        $('#txt').keydown(function (e) {
          $this = $(this)
          if (e.keyCode == 13 && $this.val()) {
            sock.send($this.val());
            $this.val('');
          }
        });
      });
    </script>
  </head>
  <body>
    <h1>Mojolicious + WebSocket</h1>
    <div id="msg">
    </div>
    <div>
      <input id="txt" type="text" />
    </div>
  </body>
</html>
