#!/usr/bin/env perl
use Mojolicious::Lite;
use Mojo::Redis2;
use Time::HiRes 'time';

my $config = plugin 'Config';

my $REDIS_CHANNEL = 'echo';

helper redis => sub { shift->stash->{redis} ||= Mojo::Redis2->new; };

get '/' => 'index';

websocket '/echo' => sub {
    my $self = shift;
    my $log  = $self->app->log;
    my $name = time;

    $log->debug('[ws] client connected');
    $self->inactivity_timeout(60);    # 60 seconds
    Scalar::Util::weaken($self);

    $self->on(
        message => sub {
            my ( $self, $msg ) = @_;
            $log->debug("[ws] < $msg");
            $self->redis->publish( $REDIS_CHANNEL => $msg );
        }
    );

    $self->on(
        finish => sub {
            my ( $self, $code, $reason ) = @_;
            $log->debug("[ws] client disconnected with status $code");
            delete $self->stash->{redis};
        }
    );

    $self->redis->on(
        message => sub {
            my ( $redis, $message, $ch ) = @_;
            return if $ch ne $REDIS_CHANNEL;
            return unless $self;
            $log->debug("[ws] > ($name) $message");
            $self->send($message);
        }
    );

    $self->redis->subscribe(
        $REDIS_CHANNEL => sub {
            my ( $redis, $err ) = @_;
            $log->error("[REDIS ERROR] subscribe error: $err") if $err;
        }
    );
};

app->start;

__DATA__

@@ index.html.ep

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Echo client</title>
    <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
    <script>
      $(function() {
        var sock;
        var port = location.port;
        sock = new WebSocket('ws://localhost:' + port + '/echo');
        sock.onopen = function(e) {
          console.log('Connected');
        }
        sock.onmessage = function(e) {
          $('<p>' + e.data + '</p>').appendTo('#msg');
        };

        $('#txt').keydown(function (e) {
          $this = $(this)
          if (e.keyCode == 13 && $this.val()) {
            sock.send($this.val());
            $this.val('');
          }
        });
      });
    </script>
  </head>
  <body>
    <h1>Mojolicious + WebSocket</h1>
    <div id="msg">
    </div>
    <div>
      <input id="txt" type="text" />
    </div>
  </body>
</html>
